### ISSUE TITLE
when will maskedCreditCard be nil in MidtransTransactionResult?

### ISSUE THREAD

**Issue by Seven163** [veritrans/Veritrans-ios-sdk#452]
I send request with method "submitPaymentDidtapped" in MidtransNewCreditCardViewController, then return success and call "payWithToken" method. I check it will call Perform credit card transaction method: performTransaction:(MidtransTransaction *)transaction completion:(void(^)(MidtransTransactionResult *result, NSError *error))completion, but result.maskedCreditCard is nil in MidtransTransactionResult, and i wanna to know when will maskedCreditCard be nil in MidtransTransactionResult.
![image](https://user-images.githubusercontent.com/14191749/55701797-1ed42000-5a07-11e9-89f7-f401a625965b.png)

**Comment by uziwuzzy** [comment]
This is a special usecase if the merchant want to manage and save the credit card token manually and doing a card registration, that's why it requires tokenStorage and maskedCreditCard value.  You can refer to the docs on card registration section https://mobile-docs.midtrans.com/?c#card-registration. Thus, it will always be nil unless there's card registration, because it's only for special usecase. 
The common usecase is to let Snap(Midtrans) handle the token storage, you only need to set a userId( For ios you can set this in the `MidtransCustomerDetails.customerIdentifier`).
So what feature do you want to use?

**Comment by kukuhx** [comment]
hi i want to install in another app? can you help me? maybe share video on youtube thank
