### ISSUE TITLE
Could not build Objective-C module 'MidtransKit'

### ISSUE THREAD

**Issue by dddOO7** [veritrans/Veritrans-ios-sdk#455]
I am integrating Midtrans SDK in my Swift Application and I am getting Could not build Objective-C module 'MidtransKit' error in my AppDelegate.swift file. 

And in I am also getting below error in other files inside Pod Framework:

Include of non-modular header inside framework module 'MidtransKit.MIdtransUICardCell': '.../Pods/MidtransCoreKit/MidtransCoreKit/MidtransCoreKit/MidtransMaskedCreditCard.h'

**Comment by uziwuzzy** [comment]
try clean and build the project. Make sure you use the xcworkspace file after doing pod install.

**Comment by dhaval-dobariya** [comment]
Already tried that many times. That's not helpful.

**Comment by uziwuzzy** [comment]
Well this is strange, It should be as simple as pod install. I tried creating empty project, and it's working fine. Are you sure you're opening the project from the .xcworkspace file generated by pod? because if you still use the default ..xcodeproj it will get error `library not found for -lMidtransCoreKit`

**Comment by dhaval-dobariya** [comment]
Yes I am sure I am using .xcworkspace file because my project already contains lots of pods. So it's not the case when I am not using .xcworkspace

**Comment by uziwuzzy** [comment]
How about reinstalling the sdk again in pod? or try pod update then clean and build the project again. Else, try creating new empty project and integrate the sdk to test. Because It should be as simple as installing other pods, and I did try myself with different project, old and new, and its working fine.
